apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-public
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8081
      port: 81
      protocol: TCP
  selector:
    app: flink-jobmanager